- name: Flush existing iptables rules
  ansible.builtin.iptables:
    flush: yes

- name: Allow established and related connections
  ansible.builtin.iptables:
    chain: INPUT
    protocol: all
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow SSH (Port 22)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: Allow HTTP (Port 80)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT

- name: Allow HTTPS (Port 443)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT

- name: Drop all other incoming connections
  ansible.builtin.iptables:
    chain: INPUT
    jump: DROP

- name: Save iptables rules
  ansible.builtin.shell: iptables-save > /etc/iptables.rules
  args:
    executable: /bin/bash
  changed_when: false

- name: Persist iptables rules on reboot (Debian/Ubuntu)
  ansible.builtin.copy:
    dest: /etc/network/if-pre-up.d/iptables
    content: |
      #!/bin/sh
      iptables-restore < /etc/iptables.rules
    mode: '0755'
  when: ansible_os_family == "Debian"

- name: Persist iptables rules on reboot (RedHat/Fedora)
  ansible.builtin.command: systemctl enable iptables
  when: ansible_os_family == "RedHat"
  changed_when: false
