- name: Install Apache
  ansible.builtin.package:
    name: "{{ apache_package }}"
    state: present

- name: Deploy Custom Homepage
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ web_root }}/index.html"
    mode: '0644'  # Set appropriate permissions

  notify: Restart Apache

- name: Start Apache
  ansible.builtin.service:
    name: "{{ apache_package }}"
    state: started
    enabled: true   # Use true instead of yes
